
services:
  - type: web
    name: viral-clip-generator
    env: python
    buildCommand: cd nr1copilot/nr1-main && python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt
    startCommand: cd nr1copilot/nr1-main && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 30
    envVars:
      - key: ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: PYTHONPATH
        value: /opt/render/project/src/nr1copilot/nr1-main
    healthCheckPath: /health
    autoDeploy: true
